name: build

permissions:
  contents: write

on:
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>1.18'
        check-latest: true
        cache: false

    - name: Build client
      run: |
        cd heavypin-client
        GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-client-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-client-windows-arm64.exe .
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-client-macos-amd64 .
        GOOS=darwin GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-client-macos-arm64 .
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-client-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-client-linux-arm64 .
      env:
        CGO_ENABLED: 0

    - name: Build server
      run: |
        cd heavypin-server
        GOOS=windows GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-server-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-server-windows-arm64.exe .
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-server-macos-amd64 .
        GOOS=darwin GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-server-macos-arm64 .
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-s -w" -o heavypin-server-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -v -ldflags="-s -w" -o heavypin-server-linux-arm64 .
      env:
        CGO_ENABLED: 0

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          heavypin-client/heavypin-client-windows-amd64.exe
          heavypin-client/heavypin-client-windows-arm64.exe
          heavypin-client/heavypin-client-macos-amd64
          heavypin-client/heavypin-client-macos-arm64
          heavypin-client/heavypin-client-linux-amd64
          heavypin-client/heavypin-client-linux-arm64
          heavypin-server/heavypin-server-windows-amd64.exe
          heavypin-server/heavypin-server-windows-arm64.exe
          heavypin-server/heavypin-server-macos-amd64
          heavypin-server/heavypin-server-macos-arm64
          heavypin-server/heavypin-server-linux-amd64
          heavypin-server/heavypin-server-linux-arm64
        tag_name: latest
        make_latest: true
